OBJECTS_TABLE_NAME = "objects_table"
LINKS_TABLE_NAME = "links_table"
TRACKS_TABLE_NAME = "tracks_table"

X_COORD_NAME = "x_coord_cmso"
Y_COORD_NAME = "y_coord_cmso"
Z_COORD_NAME = "z_coord_cmso"
FRAME_NAME = "frame_cmso"
OBJECT_NAME = "object_id_cmso"
LINK_NAME = "link_id_cmso"
